- name: myplaybook
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: installing nginx
      yum:
       name: nginx
       state: present
    - name: start nginx
      service:
       name: nginx
       state: started
    - name: installing php
      yum:
       name: php
       state: present
    - name: start php
      service:
       name: php-fpm
       state: started
      notify: restarting nginx
    - name: installing mariadb
      yum:
       name: mariadb105-server
       state: present
    - name: start mariadb
      service:
       name: mariadb
       state: started
      notify: restarting nginx
      notify: restarting php
      notify: restarting mariadb
  handlers:
     - name: restarting nginx
       service:
         name: nginx
         state: restarted
     - name: restarting php
       service:
         name: php-fpm
         state: restarted
     - name: restarting mariadb
       service:
         name: mariadb
         state: restarted




